// TiendaReactJS/componentes/Login.jsx
import React from 'react'
import ReactDom from 'react-dom'
import * as firebase from 'firebase'
import * as request from 'superagent'
import {BrowserRouter as Router, Route, Link, Redirect} from 'react-router-dom'

//---------------   Importacion de Componentes ---------------------------
import LoginFirebase from './FirebaseDB.jsx'

const USUARIODB = firebase.database().ref().child('usuarios')

class LoginForm extends React.Component{
    constructor(props){
        super(props)
        this.state = {
            email: '',
            password: '',
            mensaje: '',
        }
        this.handleChange = this.handleChange.bind(this)
        this.checkLogin = this.checkLogin.bind(this)
    }

    checkSession(){
        return sessionStorage.getItem("Session")
    }

    handleChange(event){
        if(event.target.id == "email"){
            this.setState({email: event.target.value})
        }
        if(event.target.id == "password"){
            this.setState({password: event.target.value})
        }
    }

    checkLogin(event){
        event.preventDefault()

        let objetoUsuarios
        let isLogged = 0
        let email = this.state.email.toLowerCase()
        let emailId = email.replace(/[^a-zA-Z 0-9.]+/g,'').replace(/\./g,'')
        //console.log('emailId_ :'+emailId)
        let password = this.state.password
        let mensajeLogin = ''


        let listaUsuarios = firebase.database().ref('/').child('usuarios')
        listaUsuarios.on('value', snapshot =>{
            //console.log('valores consultados tabla usuarios: '+JSON.stringify(snapshot.val()))
            objetoUsuarios = snapshot.val()
        })

        for(let i in objetoUsuarios){

           // console.log('userData_ :'+objetoUsuarios[i].usuario)

            if(objetoUsuarios[i].usuario == email){
                //console.log('Email correcto: '+objetoUsuarios[i].usuario)
                if(objetoUsuarios[i].clave == password){
                    mensajeLogin = "Iniciando Sesion"
                    sessionStorage.setItem("Session", email)
                    isLogged = 1
                }
            }
            else{
                mensajeLogin = "Las credenciales no son correctas"
            }
        }
        this.setState({mensaje : mensajeLogin})
        //console.log(mensajeLogin)
    }

    render(){
        if(this.checkSession()){
            return <Redirect to='/tienda'/>
        }

        return(
            <div className="login row">
                <div className="col s6 form-container animated fadeIn slow">
                    <form onSubmit={this.checkLogin}>
                        <h4 className="text-center white-text">Inicio de Sesion</h4>
                        <div className="col s12 input-field">
                            <input type="email" ref="email" id="email" value={this.state.email} onChange={this.handleChange} placeholder="" className="validate white-text" required aria-required="true"/>
                            <label htmlFor="email" data-error="Error en direccion email" data-success="Formato email correcto">Correo Electronico</label>
                        </div>
                        <div className="col s12 input-field">
                            <input type="password" ref="password" id="password" value={this.state.password} onChange={this.handleChange} placeholder="" className="validate white-text" required aria-required="true"/>
                            <label htmlFor="password" data-error="Contraseña no puede estar vacia" className="white-text">Contraseña</label>
                        </div>
                        <div className="col s12 center-align">
                            <div className="mensaje">
                                {this.state.mensaje}
                            </div>
                            <button type="submit" className="btn btn-success">Ingresar</button>
                        </div>
                    </form>
                </div>
            </div>
        )
    }

}

export default LoginForm

// TiendaAngular2/src/app/componentes/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Validators, FormControl, FormGroup } from '@angular/forms';
import {AngularFire, FirebaseListObservable} from 'angularfire2';
import {Router} from '@angular/router';
import { exists } from 'fs';

//-----------  import Servicios--------------
import {AuthService} from "../../servicios/auth.service"

@Component({
  selector: 'login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent implements OnInit {
    loginForm: FormGroup;
    elementos: FirebaseListObservable<any[]>;
    email: string;
    password: string;
    mensaje: string;
    listado: any[];
    test: string;

  constructor(
    private db: AngularFire,
    private auth: AuthService,
    private router: Router
    ) { 
      if(this.auth.validarSesion()){
        this.router.navigate(['tienda'])
      }

  }

  ngOnInit() {
    this.email = ""
    this.password = ""
    if(this.auth.validarSesion()){
      this.router.navigate(['/tienda'])
    }

    this.loginForm = new FormGroup({
      'email' : new FormControl('', Validators.required),
      'password' : new FormControl('', Validators.required)
    })
  }

  validarLogin(){
    if(this.loginForm.valid)
    {
      let incr : number = 0
      let correo = this.loginForm.value.email; 
      let password = this.loginForm.value.password;      
      this.db.database.list('/usuarios').subscribe(listado => {
        this.listado = listado;
        let listusuarios = JSON.parse(JSON.stringify(this.listado))
        
        listusuarios.forEach(element => {
          if(element.usuario === correo && element.clave === password)
          {
            incr = incr+1
            //console.log("Credenciales "+element.usuario+" y clave "+element.clave+" son validas");            
            sessionStorage.setItem("Session", this.loginForm.value.email)
            this.router.navigate(['tienda'])
          } 
        });
        //console.log('login value = '+incr)   
        if(incr == 0)
        { this.mensaje = 'Credenciales de inicio de sesion erroneas!!!'}    
      });

    }
  }

}


<div class="loginContainer">
  <div class="col-sm-4 form-container animated fadeIn slow text-white">
    <form [formGroup]="loginForm" (ngSubmit)="validarLogin()">
      <h4 class="text-center">Iniciar Sesion</h4>

      <div class="form-group">
        <label for="email" >Correo Electronico</label>
        <input formControlName="email" type="email" id="email" 
          class="form-control"
          pattern="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?">
        <label *ngIf="!loginForm.controls['email'].valid" class="text-red">Favor ingresar un correo electronico</label>
      </div>

      <div class="form-group">
        <label for="password" >Contraseña</label>
        <input formControlName="password" type="password" id="password" class="form-control">
        <label *ngIf="!loginForm.controls['password'].valid">Favor ingresar clave</label>
      </div>

      <div class="row text-center">
      <div class="mensaje">{{mensaje}}</div>  
            <div class="col-sm-10"> 
              <button type="submit" class="btn btn-success" [disabled]="!loginForm.valid">Ingresar</button>
            </div>  
      </div>
    </form>
  </div>
</div>
